### ISSUE TITLE
是否都支持 webview 和wkwebview？

### ISSUE THREAD

**Issue by bulolo** [cmp-cc/vue-bridge-webview#1]
是否都支持 webview 和wkwebview？

是否是可以使用类似  
https://github.com/marcuswestin/WebViewJavascriptBridge
https://github.com/zhangbozhb/WebViewBridge.Swift
在IOS上注册方法使用

**Comment by cmp-cc** [comment]
支持 webview 和 wkwebview
你在oc 或 swift 中 引入 WebViewJavascriptBridge 就可以了，写相关js调用的方法。

**Comment by yogithesymbian** [comment]
🤔
